//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:54 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:55:36 AM MDT 
//


package com.bc.ct.ws.model;

import java.util.Date;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import com.bc.ct.util.DateConverter;

public class Adapter1 extends XmlAdapter<String, Date>{

    public Date unmarshal(String value) {
        return (DateConverter.parseDateCT(value));
    }

    public String marshal(Date value) {
        return (DateConverter.printDateCT(value));
    }
}
