//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:54 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:55:36 AM MDT 
//


package com.bc.ct.ws.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clientGroup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="clientGroup">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BOISEP"/>
 *     &lt;enumeration value="BOISEW"/>
 *     &lt;enumeration value="BOISEB"/>
 *     &lt;enumeration value="BOISEC"/>
 *     &lt;enumeration value="BOISEH"/>
 *     &lt;enumeration value="BOISET"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "clientGroup")
@XmlEnum
public enum ClientGroup {

    BOISEP,
    BOISEW,
    BOISEB,
    BOISEC,
    BOISEH,
    BOISET;

    public String value() {
        return name();
    }

    public static ClientGroup fromValue(String v) {
        return valueOf(v);
    }

}
