//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.07 at 02:50:29 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.boiseinc.com/cc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bc.ct.ws.model;
