//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:54 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:55:36 AM MDT 
//


package com.bc.ct.ws.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RateQuote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateQuote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="equipment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="init" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="charges">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="charge" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="stopNum" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="meas" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="rate" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="amt" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tariffAuth" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="expDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="effDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rateRemarkList" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tracToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scac" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="totalAmt" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="terms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="route" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="miles" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ctShipMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateQuote", propOrder = {
    "equipment",
    "charges",
    "tariffAuth",
    "rateRemarkList"
})
public class RateQuote {

    @XmlElement(required = true)
    protected RateQuote.Equipment equipment;
    @XmlElement(required = true)
    protected RateQuote.Charges charges;
    @XmlElement(required = true)
    protected List<RateQuote.TariffAuth> tariffAuth;
    protected List<String> rateRemarkList;
    @XmlAttribute(name = "tracToken")
    protected String tracToken;
    @XmlAttribute(name = "scac")
    protected String scac;
    @XmlAttribute(name = "totalAmt")
    protected Float totalAmt;
    @XmlAttribute(name = "terms")
    protected String terms;
    @XmlAttribute(name = "route")
    protected String route;
    @XmlAttribute(name = "miles")
    protected Integer miles;
    @XmlAttribute(name = "currency")
    protected String currency;
    @XmlAttribute(name = "ctShipMode")
    protected String ctShipMode;

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link RateQuote.Equipment }
     *     
     */
    public RateQuote.Equipment getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateQuote.Equipment }
     *     
     */
    public void setEquipment(RateQuote.Equipment value) {
        this.equipment = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link RateQuote.Charges }
     *     
     */
    public RateQuote.Charges getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateQuote.Charges }
     *     
     */
    public void setCharges(RateQuote.Charges value) {
        this.charges = value;
    }

    /**
     * Gets the value of the tariffAuth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tariffAuth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTariffAuth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateQuote.TariffAuth }
     * 
     * 
     */
    public List<RateQuote.TariffAuth> getTariffAuth() {
        if (tariffAuth == null) {
            tariffAuth = new ArrayList<RateQuote.TariffAuth>();
        }
        return this.tariffAuth;
    }

    /**
     * Gets the value of the rateRemarkList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateRemarkList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateRemarkList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRateRemarkList() {
        if (rateRemarkList == null) {
            rateRemarkList = new ArrayList<String>();
        }
        return this.rateRemarkList;
    }

    /**
     * Gets the value of the tracToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTracToken() {
        return tracToken;
    }

    /**
     * Sets the value of the tracToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTracToken(String value) {
        this.tracToken = value;
    }

    /**
     * Gets the value of the scac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScac() {
        return scac;
    }

    /**
     * Sets the value of the scac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScac(String value) {
        this.scac = value;
    }

    /**
     * Gets the value of the totalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTotalAmt() {
        return totalAmt;
    }

    /**
     * Sets the value of the totalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTotalAmt(Float value) {
        this.totalAmt = value;
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerms(String value) {
        this.terms = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the miles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMiles() {
        return miles;
    }

    /**
     * Sets the value of the miles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMiles(Integer value) {
        this.miles = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the ctShipMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtShipMode() {
        return ctShipMode;
    }

    /**
     * Sets the value of the ctShipMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtShipMode(String value) {
        this.ctShipMode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="charge" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="stopNum" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="meas" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="rate" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="amt" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "charge"
    })
    public static class Charges {

        @XmlElement(required = true)
        protected List<RateQuote.Charges.Charge> charge;

        /**
         * Gets the value of the charge property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the charge property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCharge().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RateQuote.Charges.Charge }
         * 
         * 
         */
        public List<RateQuote.Charges.Charge> getCharge() {
            if (charge == null) {
                charge = new ArrayList<RateQuote.Charges.Charge>();
            }
            return this.charge;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="stopNum" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="meas" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="rate" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="amt" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Charge {

            @XmlAttribute(name = "stopNum")
            protected Integer stopNum;
            @XmlAttribute(name = "code")
            protected String code;
            @XmlAttribute(name = "desc")
            protected String desc;
            @XmlAttribute(name = "meas")
            protected String meas;
            @XmlAttribute(name = "rate")
            protected Float rate;
            @XmlAttribute(name = "units")
            protected Float units;
            @XmlAttribute(name = "amt")
            protected Float amt;

            /**
             * Gets the value of the stopNum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStopNum() {
                return stopNum;
            }

            /**
             * Sets the value of the stopNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStopNum(Integer value) {
                this.stopNum = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the desc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesc() {
                return desc;
            }

            /**
             * Sets the value of the desc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesc(String value) {
                this.desc = value;
            }

            /**
             * Gets the value of the meas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMeas() {
                return meas;
            }

            /**
             * Sets the value of the meas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMeas(String value) {
                this.meas = value;
            }

            /**
             * Gets the value of the rate property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getRate() {
                return rate;
            }

            /**
             * Sets the value of the rate property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setRate(Float value) {
                this.rate = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setUnits(Float value) {
                this.units = value;
            }

            /**
             * Gets the value of the amt property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getAmt() {
                return amt;
            }

            /**
             * Sets the value of the amt property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setAmt(Float value) {
                this.amt = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="init" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Equipment {

        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "init")
        protected String init;
        @XmlAttribute(name = "num")
        protected String num;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the init property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInit() {
            return init;
        }

        /**
         * Sets the value of the init property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInit(String value) {
            this.init = value;
        }

        /**
         * Gets the value of the num property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNum() {
            return num;
        }

        /**
         * Sets the value of the num property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNum(String value) {
            this.num = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="expDate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="effDate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TariffAuth {

        @XmlAttribute(name = "num")
        protected String num;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "expDate")
        @XmlJavaTypeAdapter(Adapter1 .class)
        @XmlSchemaType(name = "date")
        protected Date expDate;
        @XmlAttribute(name = "effDate")
        @XmlJavaTypeAdapter(Adapter1 .class)
        @XmlSchemaType(name = "date")
        protected Date effDate;

        /**
         * Gets the value of the num property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNum() {
            return num;
        }

        /**
         * Sets the value of the num property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNum(String value) {
            this.num = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the expDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getExpDate() {
            return expDate;
        }

        /**
         * Sets the value of the expDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpDate(Date value) {
            this.expDate = value;
        }

        /**
         * Gets the value of the effDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getEffDate() {
            return effDate;
        }

        /**
         * Sets the value of the effDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEffDate(Date value) {
            this.effDate = value;
        }

    }

}
