//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:54 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:55:36 AM MDT 
//


package com.bc.ct.ws.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="equipment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="init" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="origin">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dest">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="commoditys" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="commodity">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="wgt" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stops" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stop">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="userId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clientGroup" use="required" type="{http://www.boiseinc.com/cc}clientGroup" />
 *       &lt;attribute name="sidBol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scac" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="destCarrier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="route" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shipDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="shipMode" use="required" type="{http://www.boiseinc.com/cc}shipMode" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" default="USD" />
 *       &lt;attribute name="roundTrip" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "equipment",
    "origin",
    "dest",
    "commoditys",
    "stops"
})
@XmlRootElement(name = "RateRequest")
public class RateRequest {

    @XmlElement(required = true)
    protected RateRequest.Equipment equipment;
    @XmlElement(required = true)
    protected RateRequest.Origin origin;
    @XmlElement(required = true)
    protected RateRequest.Dest dest;
    @XmlElement(required = true)
    protected List<RateRequest.Commoditys> commoditys;
    protected List<RateRequest.Stops> stops;
    @XmlAttribute(name = "userId", required = true)
    protected String userId;
    @XmlAttribute(name = "clientGroup", required = true)
    protected ClientGroup clientGroup;
    @XmlAttribute(name = "sidBol")
    protected String sidBol;
    @XmlAttribute(name = "scac")
    protected String scac;
    @XmlAttribute(name = "destCarrier")
    protected String destCarrier;
    @XmlAttribute(name = "route")
    protected String route;
    @XmlAttribute(name = "shipDate", required = true)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "date")
    protected Date shipDate;
    @XmlAttribute(name = "shipMode", required = true)
    protected ShipMode shipMode;
    @XmlAttribute(name = "currency")
    protected String currency;
    @XmlAttribute(name = "roundTrip")
    protected Boolean roundTrip;

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link RateRequest.Equipment }
     *     
     */
    public RateRequest.Equipment getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateRequest.Equipment }
     *     
     */
    public void setEquipment(RateRequest.Equipment value) {
        this.equipment = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link RateRequest.Origin }
     *     
     */
    public RateRequest.Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateRequest.Origin }
     *     
     */
    public void setOrigin(RateRequest.Origin value) {
        this.origin = value;
    }

    /**
     * Gets the value of the dest property.
     * 
     * @return
     *     possible object is
     *     {@link RateRequest.Dest }
     *     
     */
    public RateRequest.Dest getDest() {
        return dest;
    }

    /**
     * Sets the value of the dest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateRequest.Dest }
     *     
     */
    public void setDest(RateRequest.Dest value) {
        this.dest = value;
    }

    /**
     * Gets the value of the commoditys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commoditys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommoditys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateRequest.Commoditys }
     * 
     * 
     */
    public List<RateRequest.Commoditys> getCommoditys() {
        if (commoditys == null) {
            commoditys = new ArrayList<RateRequest.Commoditys>();
        }
        return this.commoditys;
    }

    /**
     * Gets the value of the stops property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stops property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStops().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateRequest.Stops }
     * 
     * 
     */
    public List<RateRequest.Stops> getStops() {
        if (stops == null) {
            stops = new ArrayList<RateRequest.Stops>();
        }
        return this.stops;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the clientGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ClientGroup }
     *     
     */
    public ClientGroup getClientGroup() {
        return clientGroup;
    }

    /**
     * Sets the value of the clientGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientGroup }
     *     
     */
    public void setClientGroup(ClientGroup value) {
        this.clientGroup = value;
    }

    /**
     * Gets the value of the sidBol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSidBol() {
        return sidBol;
    }

    /**
     * Sets the value of the sidBol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSidBol(String value) {
        this.sidBol = value;
    }

    /**
     * Gets the value of the scac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScac() {
        return scac;
    }

    /**
     * Sets the value of the scac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScac(String value) {
        this.scac = value;
    }

    /**
     * Gets the value of the destCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestCarrier() {
        return destCarrier;
    }

    /**
     * Sets the value of the destCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestCarrier(String value) {
        this.destCarrier = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the shipDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getShipDate() {
        return shipDate;
    }

    /**
     * Sets the value of the shipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipDate(Date value) {
        this.shipDate = value;
    }

    /**
     * Gets the value of the shipMode property.
     * 
     * @return
     *     possible object is
     *     {@link ShipMode }
     *     
     */
    public ShipMode getShipMode() {
        return shipMode;
    }

    /**
     * Sets the value of the shipMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipMode }
     *     
     */
    public void setShipMode(ShipMode value) {
        this.shipMode = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        if (currency == null) {
            return "USD";
        } else {
            return currency;
        }
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the roundTrip property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRoundTrip() {
        if (roundTrip == null) {
            return false;
        } else {
            return roundTrip;
        }
    }

    /**
     * Sets the value of the roundTrip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRoundTrip(Boolean value) {
        this.roundTrip = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="commodity">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="wgt" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "commodity"
    })
    public static class Commoditys {

        @XmlElement(required = true)
        protected RateRequest.Commoditys.Commodity commodity;

        /**
         * Gets the value of the commodity property.
         * 
         * @return
         *     possible object is
         *     {@link RateRequest.Commoditys.Commodity }
         *     
         */
        public RateRequest.Commoditys.Commodity getCommodity() {
            return commodity;
        }

        /**
         * Sets the value of the commodity property.
         * 
         * @param value
         *     allowed object is
         *     {@link RateRequest.Commoditys.Commodity }
         *     
         */
        public void setCommodity(RateRequest.Commoditys.Commodity value) {
            this.commodity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="wgt" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Commodity {

            @XmlAttribute(name = "code", required = true)
            protected String code;
            @XmlAttribute(name = "desc")
            protected String desc;
            @XmlAttribute(name = "wgt", required = true)
            protected int wgt;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the desc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesc() {
                return desc;
            }

            /**
             * Sets the value of the desc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesc(String value) {
                this.desc = value;
            }

            /**
             * Gets the value of the wgt property.
             * 
             */
            public int getWgt() {
                return wgt;
            }

            /**
             * Sets the value of the wgt property.
             * 
             */
            public void setWgt(int value) {
                this.wgt = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Dest {

        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "city")
        protected String city;
        @XmlAttribute(name = "state")
        protected String state;
        @XmlAttribute(name = "zip")
        protected String zip;
        @XmlAttribute(name = "county")
        protected String county;
        @XmlAttribute(name = "nation")
        protected String nation;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the zip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZip() {
            return zip;
        }

        /**
         * Sets the value of the zip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZip(String value) {
            this.zip = value;
        }

        /**
         * Gets the value of the county property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCounty() {
            return county;
        }

        /**
         * Sets the value of the county property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCounty(String value) {
            this.county = value;
        }

        /**
         * Gets the value of the nation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNation() {
            return nation;
        }

        /**
         * Sets the value of the nation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNation(String value) {
            this.nation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="init" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Equipment {

        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "init")
        protected String init;
        @XmlAttribute(name = "num")
        protected String num;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the init property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInit() {
            return init;
        }

        /**
         * Sets the value of the init property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInit(String value) {
            this.init = value;
        }

        /**
         * Gets the value of the num property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNum() {
            return num;
        }

        /**
         * Sets the value of the num property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNum(String value) {
            this.num = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Origin {

        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "city")
        protected String city;
        @XmlAttribute(name = "state")
        protected String state;
        @XmlAttribute(name = "zip")
        protected String zip;
        @XmlAttribute(name = "county")
        protected String county;
        @XmlAttribute(name = "nation")
        protected String nation;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the zip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZip() {
            return zip;
        }

        /**
         * Sets the value of the zip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZip(String value) {
            this.zip = value;
        }

        /**
         * Gets the value of the county property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCounty() {
            return county;
        }

        /**
         * Sets the value of the county property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCounty(String value) {
            this.county = value;
        }

        /**
         * Gets the value of the nation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNation() {
            return nation;
        }

        /**
         * Sets the value of the nation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNation(String value) {
            this.nation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stop">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stop"
    })
    public static class Stops {

        @XmlElement(required = true)
        protected RateRequest.Stops.Stop stop;

        /**
         * Gets the value of the stop property.
         * 
         * @return
         *     possible object is
         *     {@link RateRequest.Stops.Stop }
         *     
         */
        public RateRequest.Stops.Stop getStop() {
            return stop;
        }

        /**
         * Sets the value of the stop property.
         * 
         * @param value
         *     allowed object is
         *     {@link RateRequest.Stops.Stop }
         *     
         */
        public void setStop(RateRequest.Stops.Stop value) {
            this.stop = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="county" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="nation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stop {

            @XmlAttribute(name = "code")
            protected String code;
            @XmlAttribute(name = "city")
            protected String city;
            @XmlAttribute(name = "state")
            protected String state;
            @XmlAttribute(name = "zip")
            protected String zip;
            @XmlAttribute(name = "county")
            protected String county;
            @XmlAttribute(name = "nation")
            protected String nation;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getState() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setState(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the zip property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZip() {
                return zip;
            }

            /**
             * Sets the value of the zip property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZip(String value) {
                this.zip = value;
            }

            /**
             * Gets the value of the county property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCounty() {
                return county;
            }

            /**
             * Sets the value of the county property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCounty(String value) {
                this.county = value;
            }

            /**
             * Gets the value of the nation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNation() {
                return nation;
            }

            /**
             * Sets the value of the nation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNation(String value) {
                this.nation = value;
            }

        }

    }

}
