//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:54 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:55:36 AM MDT 
//


package com.bc.ct.ws.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="failure" type="{http://www.boiseinc.com/cc}RateFailure"/>
 *         &lt;element name="quotes" type="{http://www.boiseinc.com/cc}RateQuote" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attribute name="tracToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "failure",
    "quotes"
})
@XmlRootElement(name = "RateResponse")
public class RateResponse {

    protected RateFailure failure;
    protected List<RateQuote> quotes;
    @XmlAttribute(name = "tracToken")
    protected String tracToken;
    @XmlTransient
    protected String rateRequestXml;

    /**
     * Gets the value of the failure property.
     * 
     * @return
     *     possible object is
     *     {@link RateFailure }
     *     
     */
    public RateFailure getFailure() {
        return failure;
    }

    /**
     * Sets the value of the failure property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateFailure }
     *     
     */
    public void setFailure(RateFailure value) {
        this.failure = value;
    }

    /**
     * Gets the value of the quotes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quotes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateQuote }
     * 
     * 
     */
    public List<RateQuote> getQuotes() {
        if (quotes == null) {
            quotes = new ArrayList<RateQuote>();
        }
        return this.quotes;
    }

    /**
     * Gets the value of the tracToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTracToken() {
        return tracToken;
    }

    /**
     * Sets the value of the tracToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTracToken(String value) {
        this.tracToken = value;
    }

	public String getRateRequestXml() {
		return rateRequestXml;
	}

	public void setRateRequestXml(String rateRequestXml) {
		this.rateRequestXml = rateRequestXml;
	}

}
